### ISSUE TITLE
"pip install mapbox-earcut" doesn't work

### ISSUE THREAD

**Issue by hugoledoux** [skogler/mapbox_earcut_python#1]
or didn't work for me, under macOS and Python 3.6.5

The reason was that the content of folder pybind11 is not pulled I think, it complains about the CMakeLIst.txt missing in that folder.

But if I clone your repo, and clone pybind11 inside and `python setup.py install` it's all working.

Cheers for making this.

**Comment by skogler** [comment]
Ah, yes, there are no prebuilt packages for macOS right now. I'll look into why the install from source does not work.

**Comment by skogler** [comment]
This should be fixed as of version 0.12.6

**Comment by hugoledoux** [comment]
I can confirm `pip install mapbox-earcut` works on macOS python 3.6.3 perfectly.

Thanks for solving this

**Comment by subhadip1242** [comment]
> Ah, yes, there are no prebuilt packages for macOS right now. I'll look into why the install from source does not work.

Can you please suggest solution for windows pc
