### ISSUE TITLE
Python 3.11 wheels missing

### ISSUE THREAD

**Issue by naveen521kk** [skogler/mapbox_earcut_python#12]
Thanks for the project. Currently, wheels for Python 3.11 is [missing on PyPI](https://pypi.org/project/mapbox-earcut/#files). Please upload it there, thanks! I think you can directly upload it for a previous release.

**Comment by naveen521kk** [comment]
cc @skogler

**Comment by skogler** [comment]
Thanks, did not get a notification on the first one. Trying to build the new wheels now

**Comment by skogler** [comment]
Released 1.0.1 which includes many more build variants. I hope this is sufficient for you. If you need me to build 1.0.0 as well I can, but its going to be more effort since its not automatic for the old versions.

**Comment by naveen521kk** [comment]
> Released 1.0.1 which includes many more build variants. I hope this is sufficient for you. If you need me to build 1.0.0 as well I can, but its going to be more effort since its not automatic for the old versions.

Thanks! I don't think I would need builds for 1.0.0 version, `1.0.1` should do.
