### ISSUE TITLE
python3.13 release

### ISSUE THREAD

**Issue by joamatab** [skogler/mapbox_earcut_python#18]
Could we create a Python 3.13 release?

Currently, we’re missing wheels for Python 3.13, which are crucial for facilitating Windows installations. Addressing this would greatly enhance compatibility and user experience.

Here’s the relevant GitHub Actions run for reference:
[GitHub Actions Run](https://github.com/gdsfactory/gdsfactory/actions/runs/12423042701)

Thank you for your support!

Best regards,

**Comment by skogler** [comment]
Hey @joamatab!

The 1.0.3 release now contains wheels for 3.13. Let me know if you see any problems with them, looks good to me so far!

**Comment by joamatab** [comment]
Awesome! it works now for windows and python3.13! Thank you Samuel
