### ISSUE TITLE
Missing win32 wheels for windows

### ISSUE THREAD

**Issue by einarf** [skogler/mapbox_earcut_python#3]
Most users seems to install 32bit python on windows because this is the default version given in the download link on python.org. It would be nice if this library also built these wheels 😄 

You can compare your wheels with the ones in moderngl : https://pypi.org/project/moderngl/5.6.2/#files

**Comment by skogler** [comment]
New build includes these, updated today. I did not think that anyone still uses 32bit versions :)

**Comment by einarf** [comment]
Thank you!
