### ISSUE TITLE
Remove setuptools_scm from dependencies?

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [skogler/mapbox_earcut_python#4]
for some unknown reason, setuptools_scm is causing me build problems with conda build.

But it doesn't seem to be used at this point, so can it simply be removed from the dependencies?

**Comment by ChrisBarker-NOAA** [comment]
BTW -- looking at this more: setup_requires is just a plain bad idea these days -- it uses setuptools easy_install before pip can get control -- which is why it's causing me trouble in conda-build.

**Comment by skogler** [comment]
Hi, sorry I did not check the issues on this one for quite a while.

Changed the build now to newest example from pybind11, should be easier to build now, since it only relies on pybind11, no cmake required anymore.
It probably requires you to remove the patches from the conda build though.

**Comment by skogler** [comment]
Closing this since no response for a while, feel free to reopen if necessary.

**Comment by ChrisBarker-NOAA** [comment]
Thanks -- we'll revisit next time we do a conda build.
