### ISSUE TITLE
Triangulation occurs in defined hole

### ISSUE THREAD

**Issue by utommo** [skogler/mapbox_earcut_python#6]
Hi, 

Thanks for providing this port. 
I am having some difficulties with the inclusion of the holes. Here's a small script of a triangle, with an inner square:

```python3
import mapbox_earcut as earcut
import numpy as np
from matplotlib import pyplot as plt

bound = np.array([[0, 0], [1, 0], [1, 1]])
hole = np.array([[0.6, 0.2],[0.8, 0.2],[0.8, 0.4],[0.6, 0.4]])
verts = np.concatenate((bound, hole),axis=0)

rings = np.array([3,7])

result = earcut.triangulate_float32(verts, rings)
result = verts[result]

bound = np.append(bound, bound[0]).reshape(-1,2)
hole = np.append(hole, hole[0]).reshape(-1,2)

plt.plot(result[:,0],result[:,1],'g')
plt.scatter(result[:,0],result[:,1],c='g')
plt.plot(hole[:,0],hole[:,1],'r')
plt.plot(bound[:,0],bound[:,1],'b')
plt.show()
```
![mapbox_earcut_mwe](https://user-images.githubusercontent.com/770589/108238407-3a52fa80-7149-11eb-975b-4cb4fccdec8e.png)

For some reason the inner square is being triangulated, despite the boundary polygon and internal square being defined as separate rings.

Did I misunderstand how to properly define the holes, or is this a bug?  Thank you very much for your time.

**Comment by skogler** [comment]
Hi, thanks for the question!

It is a misunderstanding, I will update the README when I have some spare time. The returned indices are a list of triangles, so you have to interpret each 3-sequence as a triangle. If you plot them as you did, you will connect the last vertex of a triangle with the first vertex of the next triangle.

Try this code to plot the triangles:

```python
import mapbox_earcut as earcut
import numpy as np
from matplotlib import pyplot as plt

bound = np.array([[0, 0], [1, 0], [1, 1], [0, 0]])
hole = np.array([[0.6, 0.2], [0.8, 0.2], [0.8, 0.4], [0.6, 0.4], [0.6, 0.2]])
verts = np.concatenate((bound, hole), axis=0)

rings = np.array([4, 9])

result = earcut.triangulate_float32(verts, rings)
result = verts[result]

bound = np.append(bound, bound[0]).reshape(-1, 2)
hole = np.append(hole, hole[0]).reshape(-1, 2)
for triangle_idx in range(result.shape[0] // 3):
    plt.fill(result[triangle_idx*3:triangle_idx*3+3, 0], result[triangle_idx*3:triangle_idx*3+3, 1], 'g', fill=False)
plt.scatter(result[:, 0], result[:, 1], c='g')
# plt.plot(hole[:, 0], hole[:, 1], 'r')
# plt.plot(bound[:, 0], bound[:, 1], 'b')
plt.show()
```

**Comment by utommo** [comment]
Thank you very much for the clarification and the swift response!
