### ISSUE TITLE
Out-of-bounds array access with empty input

### ISSUE THREAD

**Issue by musicinmybrain** [skogler/mapbox_earcut_python#9]
An out-of-bounds access is possible. It can be demonstrated by `test_empty_data`, although the test may pass in practice under some circumstances depending on the particular compiler and architecture.

Consider the `test_empty_data` case:

```python
 verts = np.array([]).reshape(-1, 2)
 rings = np.array([])
```

and note that the shape of `rings` is `(0,)`.

Now examine the implementation of

```cpp
template<typename CoordT, typename IndexT>
py::array_t<IndexT> triangulate(py::array_t<CoordT> vertices, py::array_t<IndexT> ring_end_indices)
```

in `main.cpp`. The values of `CoordT` and `IndexT` should not matter, but let’s assume `float` and `uint32_t`, respectively, corresponding to `triangulate_float32`.

These values of `verts`/`vertices` and `rings`/`ring_end_indices` pass the first two tests; both `(vertices.ndim() != 2)` and `(ring_end_indices.ndim() != 1)` are false.

Now we have  `auto v = vertices.unchecked();`, followed by the test `(v.shape(1) != 2)`. It is safe since we already verified that `vertices` was two-dimensional, and it also evaluates false, so execution continues in the routine.

Next we have `auto r = ring_end_indices.template unchecked<1>();`. This is valid too, since we verified `rings` is one-dimensional, but it suggests upcoming danger, as it contains no elements.

Next, in

```cpp
const ssize_t num_rings = r.shape(0);
const ssize_t num_verts = v.shape(0);
```

both sizes are (signed) zero.

The next line is

```cpp
    if (r(num_rings - 1) != num_verts)
```

which does an unchecked access of index `-1` of the `rings` array—an out-of-bounds access that invokes undefined behavior. From there, anything can happen.

In practice, this address is likely to be mapped in the process address space with a deterministic value (so, likely no segfault) that depends on compiler and architecture. Depending on what exactly is at that address, the expression may evaluate true or false, and the test may fail or not. If it does fail, it most likely looks like:

```
_______________________________ test_empty_data ________________________________
    def test_empty_data():
        verts = np.array([]).reshape(-1, 2)
        rings = np.array([])
    
>       result = earcut.triangulate_float32(verts, rings)
E       ValueError: The last value of ring_end_indices must be equal to the number of vertices!
```

It looks like the polygon-building loop should work just fine (zero iterations) in this scenario, so it should be sufficient just to make the expression `(r(num_rings - 1) != num_verts)` safe for the `num_rings == 0` case. I’ll prepare a small PR to do that.

**Comment by musicinmybrain** [comment]
> ```c++
>     if ((num_rings > 0) ? (r(num_rings - 1) != num_verts) : (num_verts > 0))
>     {   
>         throw std::invalid_argument("The last value of ring_end_indices must be equal to the number of vertices!");
>     }
> ```

That’s not right, because the ternary operator doesn’t short-circuit, so `r(-1)` is still evaluated. However, I implemented equivalent short-circuiting logic in https://github.com/skogler/mapbox_earcut_python/pull/11, and the tests now pass (including on architectures where they previously failed due to the out-of-bounds access).

**Comment by skogler** [comment]
Thanks for the great writeup! 
Definitely a bug; I was not too concerned with empty rings when writing this. 

Your fix looks correct, however, I would prefer a separate message for the case when the ring_end_indices array is empty but a list of vertices is passed.
